### ISSUE TITLE
Support swap datasets

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#10]
See here for a description of the datasets and relations needed for supporting Swap data: https://docs.google.com/document/d/13L-RecGRgyhQhBTX-fDVaPeAAPa6E8QkmVOMB6lb9e0/edit?ts=5d03f229#

**Comment by GalaJames** [comment]
Initial cut of the data is available here:

https://drive.google.com/drive/folders/1-ZMZ1V2IHYQUDnNV-u2KA6vs3TIgKcBM

Here is how it was generated:

Counterparties:
- 10 counterparties were generated, using the record_count from the config file.

Swap Contracts
- The following config setting was used for swap_contracts:  
"swap_per_counterparty": {"min":"5", "max":"5"}
- This resulted in 5 swap contracts per counterparty, giving a total of 50 swap contracts.

Swap Positions
- The following config setting was used for swap_positions:  
"start_date":"20190701", 
            "ins_per_swap": {"min":"5", "max":"5"}
- This resulted in 5 swap positions per swap contract, giving a total of 250 positions per day.  With a start date of 1st July, this resulted in positions created for 4 days, giving a total of 1,000 positions per position type.  As there are three position types, we end up with 3,000 positions (5 * 50 * 4 * 3), 1,000 positions per position type.

Cashflows
- The following config was used for cashflows:
"start_date":"20190701", 
            "cashflow_generation" : [
            {
                "cashFlowType": "INT",
                "cashFlowAccrual": "DAILY",
                "cashFlowAccrualProbability": 100,
                "cashFlowPaydatePeriod": "END_OF_MONTH"
            },
            {
                "cashFlowType": "DIV",
                "cashFlowAccrual": "QUARTERLY",
                "cashFlowAccrualProbability": 100,
                "cashFlowPaydatePeriod": "END_OF_HALF"
            },
            {
                "cashFlowType": "EQUITY_PN_L",
                "cashFlowAccrual": "CHANCE_ACCRUAL",
                "cashFlowAccrualProbability": 60,
                "cashFlowPaydatePeriod": "END_OF_MONTH"
            }]
 - This results in 1,000 cashflows being generated per unique combination of swap contract, instrument and day (50 swap contracts * 5 instruments * 4 days) for the cashflow type "INT".  
 - No cashflows of type "DIV" are created because the date range doesn't span a quarter.  
 - Roughly 600 cashflows are generated for cashflow type "EQUITY_PN_L", this is based on 60% of the 1,000 cashflows that were created for type "INT".

**Comment by k96payne** [comment]
Hey James,  the logic for generating each dataset is correct for our use case. There are a couple of changes to the generated data we will need.

- Regarding the Positions and Instruments datasets... different position records with the same instrument id have different ric's. In addition to this, the position ric's are also different from the ric on the Instrument record with the corresponding instrument id. We need: either the ric sub-scripted with "positions" and "instrument" (e.g., positions_ric) OR the ric in each position to match its ric in the corresponding Instrument record. I realize that all of the extra data is randomly generated so it doesn't logically make sense, but since we have two datasets with the same field, we'll need them to logically make sense or differ in name for our current use case.

- Regarding Swap Contracts and Counter Parties... you already created an issue for this, but we'll need the don't-care field names to differ in naming

- Regarding the output format... Is it possible to get it in JSONL format instead of in a list? (e.g., {"field": value, ...}\n{"field":value,...}) I think we spoke about this earlier but it probably wasn't communicated well enough. http://jsonlines.org

Overall, everything is looking really good. Nice work on this. We really appreciate it!

**Comment by k96payne** [comment]
Follow-up comments...

>> kyle.payne [11:17 AM]
One more thing I forgot to mention, can we change all date time formats to yyyyMMddss (seconds if applicable) format? There are examples in the data gen documentation I created for our use case.

EDIT: defer to Ari

>> packer [Today at 11:22 AM]
or we can use a standard like ISO 8601 https://www.w3.org/TR/NOTE-datetime
1 reply
    >> packer
    and in UTC, e.g., 2011-08-12T20:17:46.384Z

>> barber [11:28 AM]
on the instrument ids -- we're just going to remove that field altogether, right?

so that first issue goes away

>> kyle.payne [11:29 AM]
That works!

**Comment by GalaJames** [comment]
A new set of files is available [here](https://drive.google.com/drive/folders/1-ZMZ1V2IHYQUDnNV-u2KA6vs3TIgKcBM) with the following changes:
 - Output using the JSONL format
 - Dates output using ISO 8601
 - instrument_id removed from swap_positions dataset
 - prefixed the domain object name to any dummy fields (I have done this crudely for now, I have a separate issue open to look at how this is done and make it configurable).

**Comment by k96payne** [comment]
The ric in the positions dataset currently changes for each effective date of the same position. The ric seems to be randomly generated. It will need to be constant since this is what shows the underlying security of the position. The ric should now correlate with the range of instruments per swap configuration since we dropped the instrument_id. Each ric should be unique in the instruments dataset if this is not done already.

**Comment by k96payne** [comment]
The long_short flag should stay the same on the cash flows for the entirety of that position on the security.

**Comment by k96payne** [comment]
kyle.payne [Today at 10:23 AM]
Hey guys, I just added another comment to the swap data gen issue. I noticed that the long short flag changes on different cash flow records for the same instrument. The position should be either a long or short position for the entirety of the position (the flag should stay the same for each cash flow record for the corresponding instrument).

22 replies

packer  [6 hours ago]
Having the position stay long or short for it's lifetime would definitely be a simplifying assumption. IRL it could go from long to short and vice versa. In this case, the long/short flag on the cash flow would have to correspond to whether the position is long or short, so keeping the position long or short for it's lifetime is reasonable. (edited)


barber  [6 hours ago]
also, wouldn't it depend on which cashflow we're talking about?


barber  [6 hours ago]
if it's a mark to market cashflow, that could go in either direction


packer  [6 hours ago]
The long/short flag in this case corresponds the direction of the position. It is effectively denormalized onto the cash flow for a position with the same effective date.


packer  [6 hours ago]
This is a quirk of our particular use case. Perhaps we should name it more descriptively to reflect this.


barber  [6 hours ago]
yes, that is a bit odd


barber  [6 hours ago]
copious documentation and commentary around that, please


james.turner  [6 hours ago]
I'll fix this - I'm re-working how the dependent domain objects work at the moment, I'll factor in this issue.


kyle.payne  [6 hours ago]
I'll add these comments into the issue replies


packer  [6 hours ago]
@barber If it was just describing the direction of the cash movement, then it wouldn't be adding any information and would be meaningless.


barber  [6 hours ago]
b/c the cash quantity is signed already?


james.turner  [3 hours ago]
Just to confirm, should the long/short flag stay the same for each instrument for a given position?  E.g. say we have swap contract 1, which has 50 instruments, should all positions for swap contract 1 be long or short, or can it differ on a per instrument basis?


james.turner  [3 hours ago]
I've uploaded a new set of files on the basis that the long/short remains the same across positions on all instruments for a given swap contract, I can easily correct it if that's not the case.  I've also fixed the RIC issue and made the timestamps more meaningful


packer  [3 hours ago]
It can differ per instrument


packer  [3 hours ago]
If you think about it, one client can have both long and short positions in different instruments.


packer  [3 hours ago]
The long/short flag on the cash flow should correspond to whether the position is long or short on the same instrument.


james.turner  [3 hours ago]
Ah OK, I assumed a single swap contract represents either just long or short


packer  [3 hours ago]
Nope - it's the position that's long or short.


james.turner  [3 hours ago]
Got it


james.turner  [3 hours ago]
I'll fix it


james.turner  [3 hours ago]
Fixed, latest files here: https://drive.google.com/drive/folders/1-ZMZ1V2IHYQUDnNV-u2KA6vs3TIgKcBM


james.turner  [3 hours ago]
Just for my own understanding....I had previously thought the swap contract represented a single swap trade, and that it could have multiple underlyings (hence multiple instruments per swap contract). So based on the comments above, does that mean a single swap trade can have different permutations of long/short underlyings?

**Comment by k96payne** [comment]
james.turner [Today at 11:37 AM]
Question - how should  the quarterly cashflows work?  Should they just be generated for each quarter-end date between the start and end dates?
2 replies

kyle.payne  [4 hours ago]
The cash flow effective date can accrue at the end of each quarter (March 31, June 30, September 30, December 31)

Someone can correct me if it should be done a different way.

james.turner  [4 hours ago]
Thanks - that was my understanding

**Comment by k96payne** [comment]
Notes on meeting today:

- add "book" to counterparties dataset 
    * 1 to 1 mapping with counterparty_id
    * each book value is a unique String with 5 capital letters (e.g., "AAAAB")
- Add "td_quantity" to positions dataset
    * integer value
    * negative value if corresponding cash flow for position is Short
    * position value if corresponding cash flow for position is Long
    * the value can change between S/I/E position types on the same effective date so it can be randomly generated
- ric on cashflows dataset instead of instrument id (it was mentioned this was changed in one of the updates but I still wanted to add it here)

**Comment by GalaJames** [comment]
Latest dataset is ready for review here:

https://drive.google.com/drive/folders/1-ZMZ1V2IHYQUDnNV-u2KA6vs3TIgKcBM

**Comment by k96payne** [comment]
I have been reviewing the most up to date data and have noticed something. RIC's are missing from some positions and cashflows. We will need to have all positions be positions containing RIC's and all cashflows have the corresponding RIC's.

**Comment by GalaJames** [comment]
This has now been fixed, latest dataset is here:

https://drive.google.com/drive/folders/1-ZMZ1V2IHYQUDnNV-u2KA6vs3TIgKcBM

The issue was that currently the instruments dataset contains cash and stock instruments and the cash instruments don't have RICs.  So when an instrument is picked at random, it can be a cash instrument.  Given we have the "cash balance" domain object, I think it's logical to make the instruments dataset only for securities.

**Comment by k96payne** [comment]
joe.bellott [6:25 AM]
The swap_datasets branch should now be functional for generating large datasets with fewer system requirements. I've ran some small-scale tests to determine expected run time as well as size of output for this use-case. If my local machine was to generate 10 years of data, it would take ~6 days, and take ~5TB of storage. There will be slight variation around this due to the randomness of generation.

The on-branch config reflects that provided above, with 2 alterations:
1) Smaller value for objects-per-file, as when too large this impacts memory requirements.
2) Added "batch_size" config for Cashflows and Swap Positions. This reflects the number of rows from the dependency database that are loaded into memory at a time when generating these domain objects. My local machine could handle a value of 1,000,000 it's likely the case that this can be increased.

I have implemented some optimisations to reduce the time required to generate data, from ~10 days down to the now ~6. I will continue working on this in the meantime and edit here if any further improvements are made.

**Comment by k96payne** [comment]
joe.bellott [Today at 11:38 AM]
That's a side effect of the maximum number of unique instruments available within our configuration. There are 25 exchanges, and 3435 tickers, meaning a maximum of 85,875 unique RICs. If I recall correctly James implemented there only being unique selections, but when 1 million are requested the expected number of repeats for each is 11/12. I'll double check the logic still ensures no duplication up to a point however.
3 replies

kyle.payne  [6 minutes ago]
Could we make the RIC longer in length in order to avoid this?

james.turner  [5 minutes ago]
Depends if we care whether or not it follows the valid RIC format.

james.turner  [4 minutes ago]
I don't think it does ensure uniqueness currently.  So there will be two issues;
1) Ensure the uniqueness of RICs
2) Extend the available number of tickers/exchanges to ensure we have enough available to generate the required number of unique RICs
